---

- name: Añade línea al backup 
  hosts: all
  vars:
      - tmpfile: "/tmp/output"

  tasks:

    - name: Insertar linea
      lineinfile:
          path: /etc/backup/include
          line: /srv/websites
      register: out


